-- GENERATED FILE — do not edit by hand.
-- Source: packages/shared/src/config/schema.ts · Regenerate: pnpm gen:config-seed

insert into public.config (key, value, schema, description) values
  ('plan_price_ceiling', '99'::jsonb, '{"type":"number","minimum":0}'::jsonb, 'Ceiling (₪/month) above which the admin plan editor warns (never blocks) when creating/repricing a plan.'),
  ('unit_rules', '{"max_small_bags_per_unit":3,"max_kg_per_unit":8,"oversized_multiplier":2,"small_4to6_units":2,"max_units_per_request":6}'::jsonb, '{"type":"object","properties":{"max_small_bags_per_unit":{"type":"integer","exclusiveMinimum":0},"max_kg_per_unit":{"type":"number","exclusiveMinimum":0},"oversized_multiplier":{"type":"integer","exclusiveMinimum":0},"small_4to6_units":{"type":"integer","exclusiveMinimum":0},"max_units_per_request":{"type":"integer","exclusiveMinimum":0}},"required":["max_small_bags_per_unit","max_kg_per_unit","oversized_multiplier","small_4to6_units","max_units_per_request"],"additionalProperties":false}'::jsonb, 'Unit counting rules: 1 large bag OR ≤max_small_bags_per_unit small bags (≤max_kg_per_unit kg) = 1 unit; oversized/overweight = oversized_multiplier units; 4–6 small bags = small_4to6_units units. max_units_per_request caps a single request (enforced in the submit RPC).'),
  ('picker_payout_per_unit_exvat', '7'::jsonb, '{"type":"number","minimum":0}'::jsonb, 'Picker payout per unit, ₪ excluding VAT. Snapshotted onto the claim at claim time — config edits never change in-flight claims.'),
  ('net_display_factor', '0.7143'::jsonb, '{"type":"number","exclusiveMinimum":0,"maximum":1}'::jsonb, 'Factor applied to the ex-VAT payout for the "₪N נטו" display shown to pickers (7.00 × 0.7143 ≈ ₪5 נטו). Display only — never affects actual payout.'),
  ('vat_rate', '0.18'::jsonb, '{"type":"number","minimum":0,"maximum":1}'::jsonb, 'VAT rate. Snapshotted per payout run; applied only for tax_status=''murshe'' pickers on self-billed invoices.'),
  ('payment_fee_fixed', '1.5'::jsonb, '{"type":"number","minimum":0}'::jsonb, 'Fixed payment processing fee (₪) per charge — reporting/metrics only, never charged to users.'),
  ('request_ttl_options', '{"options":[{"key":"noon","cutoff":"12:00"},{"key":"evening","cutoff":"18:00"},{"key":"today","cutoff":"23:00"}],"default":"today"}'::jsonb, '{"type":"object","properties":{"options":{"type":"array","items":{"type":"object","properties":{"key":{"type":"string","minLength":1},"cutoff":{"type":"string","pattern":"^([01]\\d|2[0-3]):[0-5]\\d$"}},"required":["key","cutoff"],"additionalProperties":false},"minItems":1},"default":{"type":"string","minLength":1}},"required":["options","default"],"additionalProperties":false}'::jsonb, 'TTL deadline chips on the submit sheet. Labels come from strings keys "ttl.<key>" (seeded: noon="עד הצהריים", evening="עד 18:00", today="היום"). Each option maps to a local cutoff time; the request''s expires_at is snapshotted at submit. Chips whose cutoff already passed today are hidden in the app.'),
  ('claim_to_scan_minutes', '45'::jsonb, '{"type":"integer","exclusiveMinimum":0}'::jsonb, 'Minutes a picker has from claim (or from bag-out confirmation in confirm-first flow) until bin-QR scan, before the claim lapses as a no-show. Snapshotted as claims.deadline_at.'),
  ('code_reveal_window_minutes', '10'::jsonb, '{"type":"integer","exclusiveMinimum":0}'::jsonb, 'Maximum minutes a revealed building entry code stays displayed (never beyond the claim deadline). Every reveal is audited.'),
  ('scan_grace_minutes', '60'::jsonb, '{"type":"integer","exclusiveMinimum":0}'::jsonb, 'Grace period after the claim deadline for a picker who already marked the bags COLLECTED but hasn''t scanned the bin QR. When it lapses too, the pickup auto-completes (paid, flagged auto_completed for the admin board) — the bags are physically gone, so reposting would be wrong.'),
  ('noshow_action', '{"repost":true,"payout_boost_pct":0,"resident_credit_units":1,"picker_strike":1}'::jsonb, '{"type":"object","properties":{"repost":{"type":"boolean"},"payout_boost_pct":{"type":"integer","minimum":0},"resident_credit_units":{"type":"integer","minimum":0},"picker_strike":{"type":"integer","minimum":0}},"required":["repost","payout_boost_pct","resident_credit_units","picker_strike"],"additionalProperties":false}'::jsonb, 'What happens when a claim lapses (picker no-show): repost the request to the open pool (optionally boosting payout by payout_boost_pct %), grant the resident resident_credit_units bag credits PER AFFECTED UNIT (1 = made whole), add strikes to the picker.'),
  ('expiry_action', '{"resident_credit_units":1}'::jsonb, '{"type":"object","properties":{"resident_credit_units":{"type":"integer","minimum":0}},"required":["resident_credit_units"],"additionalProperties":false}'::jsonb, 'What happens when an open request passes its TTL unclaimed: the resident automatically receives resident_credit_units bag credits PER REQUESTED UNIT (1 = made whole), zero-touch.'),
  ('strikes_to_suspend', '3'::jsonb, '{"type":"integer","exclusiveMinimum":0}'::jsonb, 'Active (non-revoked) strikes at which a picker is automatically suspended.'),
  ('credit_expiry_days', '90'::jsonb, '{"type":"integer","exclusiveMinimum":0}'::jsonb, 'Days until bag credits from expiry/no-show/building-meter grants expire. (Referral credits use referral.expiry_days; kartisiya uses kartisiya.validity_days.)'),
  ('max_active_claim_groups', '1'::jsonb, '{"type":"integer","exclusiveMinimum":0}'::jsonb, 'How many claim groups (buildings) a picker may hold simultaneously.'),
  ('poa_version', '"poa-selfbill-2026-08"'::jsonb, '{"type":"string","minLength":1}'::jsonb, 'Version tag of the self-billing power-of-attorney consent text pickers sign at onboarding. Bump when the legal text changes; stored on each picker''s consent record.'),
  ('boost', '{"enabled":false,"user_fee":4,"payout_bump":2}'::jsonb, '{"type":"object","properties":{"enabled":{"type":"boolean"},"user_fee":{"type":"number","minimum":0},"payout_bump":{"type":"number","minimum":0}},"required":["enabled","user_fee","payout_bump"],"additionalProperties":false}'::jsonb, 'Boost: resident pays user_fee (₪) to bump the picker payout by payout_bump (₪) on one request. OFF until the founder enables.'),
  ('backstop', '{"enabled":false,"user_price":15,"ttl_hours":24}'::jsonb, '{"type":"object","properties":{"enabled":{"type":"boolean"},"user_price":{"type":"number","minimum":0},"ttl_hours":{"type":"integer","exclusiveMinimum":0}},"required":["enabled","user_price","ttl_hours"],"additionalProperties":false}'::jsonb, 'Backstop: paid rescue option offered on expired requests (manual-dispatch lever). The relisted request stays open ttl_hours. OFF until the founder enables.'),
  ('on_demand_single', '{"enabled":true,"price":22}'::jsonb, '{"type":"object","properties":{"enabled":{"type":"boolean"},"price":{"type":"number","minimum":0}},"required":["enabled","price"],"additionalProperties":false}'::jsonb, 'One-off pickup for non-subscribers: single request at this price (₪), charged per request.'),
  ('extra_roll', '{"enabled":true,"price":15}'::jsonb, '{"type":"object","properties":{"enabled":{"type":"boolean"},"price":{"type":"number","minimum":0}},"required":["enabled","price"],"additionalProperties":false}'::jsonb, 'Extra bag-roll order for subscribers, price in ₪.'),
  ('kartisiya', '{"enabled":false,"price":95,"units":8,"validity_days":90}'::jsonb, '{"type":"object","properties":{"enabled":{"type":"boolean"},"price":{"type":"number","minimum":0},"units":{"type":"integer","exclusiveMinimum":0},"validity_days":{"type":"integer","exclusiveMinimum":0}},"required":["enabled","price","units","validity_days"],"additionalProperties":false}'::jsonb, 'Punch-card (כרטיסיה): prepaid bundle of units with limited validity. Schema + flag only in MVP — no UI until legal check passes.'),
  ('referral', '{"enabled":true,"reward_units_each_side":3,"expiry_days":60,"monthly_stack_cap":6}'::jsonb, '{"type":"object","properties":{"enabled":{"type":"boolean"},"reward_units_each_side":{"type":"integer","exclusiveMinimum":0},"expiry_days":{"type":"integer","exclusiveMinimum":0},"monthly_stack_cap":{"type":"integer","exclusiveMinimum":0}},"required":["enabled","reward_units_each_side","expiry_days","monthly_stack_cap"],"additionalProperties":false}'::jsonb, 'Referral program: both sides receive reward_units_each_side bag credits when the referee''s first payment settles. Pending referrals expire after expiry_days; a referrer can earn at most monthly_stack_cap referral units per calendar month.'),
  ('building_meter', '{"enabled":true,"tiers":[{"doors":5,"bonus_units_all":1},{"doors":10,"bonus_units_all":2},{"doors":20,"bonus_units_all":3}]}'::jsonb, '{"type":"object","properties":{"enabled":{"type":"boolean"},"tiers":{"type":"array","items":{"type":"object","properties":{"doors":{"type":"integer","exclusiveMinimum":0},"bonus_units_all":{"type":"integer","exclusiveMinimum":0}},"required":["doors","bonus_units_all"],"additionalProperties":false},"minItems":1}},"required":["enabled","tiers"],"additionalProperties":false}'::jsonb, 'Building meter: when a building reaches `doors` active subscriptions, every active door receives bonus_units_all bag credits (once per tier per building). Social proof + bag bonuses ONLY — never gates service.'),
  ('bag_formats', '{"large":{"units_per_bag":1,"roll_count":18},"small":{"bags_per_unit":3,"roll_count":54}}'::jsonb, '{"type":"object","properties":{"large":{"type":"object","properties":{"units_per_bag":{"type":"integer","exclusiveMinimum":0},"roll_count":{"type":"integer","exclusiveMinimum":0}},"required":["units_per_bag","roll_count"],"additionalProperties":false},"small":{"type":"object","properties":{"bags_per_unit":{"type":"integer","exclusiveMinimum":0},"roll_count":{"type":"integer","exclusiveMinimum":0}},"required":["bags_per_unit","roll_count"],"additionalProperties":false}},"required":["large","small"],"additionalProperties":false}'::jsonb, 'Bag roll formats: large = 1 unit per bag, 18 bags per roll; small = 3 bags per unit, 54 bags per roll.'),
  ('photo_retention_days', '90'::jsonb, '{"type":"integer","exclusiveMinimum":0}'::jsonb, 'Days leak-decline photos are retained in private storage before automatic deletion.'),
  ('rate_limits', '{"otp_per_phone_per_hour":5,"claim_per_picker_per_hour":20,"reveal_per_claim":5}'::jsonb, '{"type":"object","properties":{"otp_per_phone_per_hour":{"type":"integer","exclusiveMinimum":0},"claim_per_picker_per_hour":{"type":"integer","exclusiveMinimum":0},"reveal_per_claim":{"type":"integer","exclusiveMinimum":0}},"required":["otp_per_phone_per_hour","claim_per_picker_per_hour","reveal_per_claim"],"additionalProperties":false}'::jsonb, 'Abuse limits enforced inside the RPCs / SMS hook (not only at the edge).'),
  ('timezone', '"Asia/Jerusalem"'::jsonb, '{"type":"string","minLength":1}'::jsonb, 'IANA timezone used to resolve TTL cutoff times and daily jobs.'),
  ('billing_retry', '{"max_attempts":4,"min_hours_between":24}'::jsonb, '{"type":"object","properties":{"max_attempts":{"type":"integer","exclusiveMinimum":0},"min_hours_between":{"type":"integer","minimum":0}},"required":["max_attempts","min_hours_between"],"additionalProperties":false}'::jsonb, 'Failed-renewal retry policy: a past_due subscription is re-charged at most once every min_hours_between hours, up to max_attempts failed attempts — then the subscription is canceled (zero-touch, resident notified).'),
  ('plan_survey', '{"bags_week":[{"min":2,"max":3,"midpoint":2.5},{"min":4,"max":6,"midpoint":5},{"min":7,"max":null,"midpoint":8}],"household":[{"min":1,"max":2,"factor":0.75},{"min":3,"max":4,"factor":1},{"min":5,"max":null,"factor":1.3}]}'::jsonb, '{"type":"object","properties":{"bags_week":{"type":"array","items":{"type":"object","properties":{"min":{"type":"integer","exclusiveMinimum":0},"max":{"anyOf":[{"type":"integer","exclusiveMinimum":0},{"type":"null"}]},"midpoint":{"type":"number","exclusiveMinimum":0}},"required":["min","max","midpoint"],"additionalProperties":false},"minItems":1},"household":{"type":"array","items":{"type":"object","properties":{"min":{"type":"integer","exclusiveMinimum":0},"max":{"anyOf":[{"type":"integer","exclusiveMinimum":0},{"type":"null"}]},"factor":{"type":"number","exclusiveMinimum":0}},"required":["min","max","factor"],"additionalProperties":false},"minItems":1}},"required":["bags_week","household"],"additionalProperties":false}'::jsonb, 'Plan-recommendation survey on the plan screen: bags_week chips are weekly bag-count ranges (midpoint drives the estimate); household chips multiply the estimate by factor. Chip labels render from min/max (e.g. 2–3, 7+). max=null means open-ended.'),
  ('service_enabled', 'true'::jsonb, '{"type":"boolean"}'::jsonb, 'Global kill switch: when false, new request submission is disabled everywhere (existing in-flight requests still finish).'),
  ('payment_provider', '"mock"'::jsonb, '{"type":"string","enum":["mock","payplus","cardcom","tranzila"]}'::jsonb, 'Which PaymentProvider adapter the edge functions instantiate. Switching mock → real PSP is a config edit, not a deploy.'),
  ('mock_payment', '{"settle_delay_seconds":2,"outcome":"settle"}'::jsonb, '{"type":"object","properties":{"settle_delay_seconds":{"type":"integer","minimum":0},"outcome":{"type":"string","enum":["settle","fail"]}},"required":["settle_delay_seconds","outcome"],"additionalProperties":false}'::jsonb, 'Mock PSP behavior: how long after chargeToken the simulated webhook settles, and whether it settles or fails (for testing).')
on conflict (key) do update
  set schema = excluded.schema,
      description = excluded.description;
