-- All user-facing copy (he primary, en fallback). Admin-editable via the
-- strings editor (api.admin_set_string). Push templates use {placeholders}
-- resolved by the notify-worker at send time.
insert into public.strings (key, locale, value) values

-- ── app ─────────────────────────────────────────────────────────────────────
('app_name',                'he', 'פינוי+'),
('app_name',                'en', 'Pinui+'),

-- ── auth / onboarding (resident) ───────────────────────────────────────────
('auth.phone_title',        'he', 'מה מספר הטלפון שלך?'),
('auth.phone_title',        'en', 'What''s your phone number?'),
('auth.otp_title',          'he', 'הזינו את הקוד ששלחנו'),
('auth.otp_title',          'en', 'Enter the code we sent'),
('auth.otp_resend',         'he', 'שליחת קוד חדש'),
('auth.otp_resend',         'en', 'Resend code'),
('auth.mode_title',         'he', 'איך תרצו להשתמש באפליקציה?'),
('auth.mode_title',         'en', 'How would you like to use the app?'),
('auth.mode_resident',      'he', 'אני רוצה שיפנו לי שקיות'),
('auth.mode_resident',      'en', 'I want my bags picked up'),
('auth.mode_picker',        'he', 'אני רוצה להרוויח מפינוי שקיות'),
('auth.mode_picker',        'en', 'I want to earn by picking up bags'),

('onboarding.address_title','he', 'איפה אתם גרים?'),
('onboarding.address_title','en', 'Where do you live?'),
('onboarding.city',         'he', 'עיר'),
('onboarding.city',         'en', 'City'),
('onboarding.street',       'he', 'רחוב'),
('onboarding.street',       'en', 'Street'),
('onboarding.house_number', 'he', 'מספר בית'),
('onboarding.house_number', 'en', 'House number'),
('onboarding.floor',        'he', 'קומה'),
('onboarding.floor',        'en', 'Floor'),
('onboarding.apartment',    'he', 'דירה'),
('onboarding.apartment',    'en', 'Apartment'),
('onboarding.entry_code_title', 'he', 'קוד כניסה ללובי (אם יש)'),
('onboarding.entry_code_title', 'en', 'Lobby entry code (if any)'),
('onboarding.door_note',    'he', 'איך מזהים את הדלת? (לא חובה)'),
('onboarding.door_note',    'en', 'How to spot your door (optional)'),

('trust.title',             'he', 'הקוד שלכם שמור'),
('trust.title',             'en', 'Your code is protected'),
('trust.encrypted',         'he', 'מוצפן — הקוד נשמר מוצפן ואף אחד לא רואה אותו, גם לא אנחנו'),
('trust.encrypted',         'en', 'Encrypted — stored encrypted; nobody can read it, not even us'),
('trust.timeboxed',         'he', 'מוגבל בזמן — נחשף לשליח רק בזמן איסוף פעיל, ונעלם אחריו'),
('trust.timeboxed',         'en', 'Time-boxed — revealed to a picker only during an active pickup, then gone'),
('trust.audited',           'he', 'מתועד — כל חשיפה של הקוד נרשמת: מי, מתי ולאיזו בקשה'),
('trust.audited',           'en', 'Audited — every reveal is logged: who, when, which request'),

-- ── plan picker ─────────────────────────────────────────────────────────────
('plan.title',              'he', 'כמה שקיות אתם מוציאים?'),
('plan.title',              'en', 'How many bags do you take out?'),
('plan.q_household',        'he', 'כמה נפשות בבית?'),
('plan.q_household',        'en', 'How many people at home?'),
('plan.q_bags_week',        'he', 'כמה שקיות בשבוע בערך?'),
('plan.q_bags_week',        'en', 'Roughly how many bags a week?'),
('plan.q_format',           'he', 'איזה גודל שקית נוח לכם?'),
('plan.q_format',           'en', 'Which bag size suits you?'),
('plan.format_large',       'he', 'גדולות (רגילות)'),
('plan.format_large',       'en', 'Large (regular)'),
('plan.format_small',       'he', 'קטנות (עד 3 = פינוי אחד)'),
('plan.format_small',       'en', 'Small (up to 3 = one pickup)'),
('plan.recommended',        'he', 'מומלץ לכם'),
('plan.recommended',        'en', 'Recommended for you'),
('plan.S.name',             'he', 'קטן'),
('plan.S.name',             'en', 'Small'),
('plan.M.name',             'he', 'בינוני'),
('plan.M.name',             'en', 'Medium'),
('plan.L.name',             'he', 'גדול'),
('plan.L.name',             'en', 'Large'),
('plan.per_month',          'he', 'לחודש'),
('plan.per_month',          'en', '/month'),
('plan.units_included',     'he', '{units} פינויים בחודש'),
('plan.units_included',     'en', '{units} pickups a month'),
('plan.bags_included',      'he', 'כולל גליל שקיות עד הבית'),
('plan.bags_included',      'en', 'Bag roll delivered — included'),
('plan.no_rollover',        'he', 'שקיות שלא נוצלו אינן נצברות'),
('plan.no_rollover',        'en', 'Unused pickups don''t roll over'),
('plan.pay_cta',            'he', 'להתחיל מנוי'),
('plan.pay_cta',            'en', 'Start subscription'),
('plan.upgrade_title',      'he', 'נגמרו הפינויים החודש'),
('plan.upgrade_title',      'en', 'You''re out of pickups this month'),
('plan.upgrade_body',       'he', 'שדרוג משתלם יותר לפי מחיר לפינוי:'),
('plan.upgrade_body',       'en', 'Upgrading costs less per pickup:'),
('plan.upgrade_cta',        'he', 'לשדרג עכשיו'),
('plan.upgrade_cta',        'en', 'Upgrade now'),
('plan.price_per_unit',     'he', '{price} לפינוי'),
('plan.price_per_unit',     'en', '{price} per pickup'),

-- ── resident HOME ───────────────────────────────────────────────────────────
('home.big_button',         'he', 'השקית מוכנה'),
('home.big_button',         'en', 'Bag''s ready'),
('home.allowance_left',     'he', 'נשארו {units} פינויים'),
('home.allowance_left',     'en', '{units} pickups left'),
('home.credits_left',       'he', '+{units} זיכויים'),
('home.credits_left',       'en', '+{units} credits'),
('home.building_strip',     'he', '{doors} שכנים בבניין כבר איתנו'),
('home.building_strip',     'en', '{doors} neighbors in your building are in'),

-- ── submit sheet ────────────────────────────────────────────────────────────
('submit.title',            'he', 'השקית בחוץ ליד הדלת? מעולה'),
('submit.title',            'en', 'Bag''s outside your door? Great'),
('submit.deadline_label',   'he', 'עד מתי לאסוף?'),
('submit.deadline_label',   'en', 'Pick up by when?'),
('submit.units_label',      'he', 'כמה יחידות?'),
('submit.units_label',      'en', 'How many units?'),
('submit.unit_hint',        'he', 'שקית גדולה אחת או עד 3 קטנות = פינוי אחד'),
('submit.unit_hint',        'en', 'One large bag or up to 3 small = one unit'),
('submit.cta',              'he', 'לפרסם בקשה'),
('submit.cta',              'en', 'Post request'),
('ttl.noon',                'he', 'עד הצהריים'),
('ttl.noon',                'en', 'By noon'),
('ttl.evening',             'he', 'עד 18:00'),
('ttl.evening',             'en', 'By 6pm'),
('ttl.today',               'he', 'היום'),
('ttl.today',               'en', 'Today'),

-- ── active request card ─────────────────────────────────────────────────────
('request.waiting',         'he', 'מחפשים מפנה…'),
('request.waiting',         'en', 'Finding a picker…'),
('request.claimed',         'he', 'מישהו בדרך אליכם 🙌'),
('request.claimed',         'en', 'Someone''s on the way 🙌'),
('request.collected',       'he', 'השקית נאספה ✓'),
('request.collected',       'en', 'Bag collected ✓'),
('request.done_title',      'he', 'בוצע! השקית בפחים'),
('request.done_title',      'en', 'Done! Bag''s in the bins'),
('request.expired_title',   'he', 'לא הספקנו הפעם — קיבלתם זיכוי'),
('request.expired_title',   'en', 'We missed this one — you got a credit'),
('request.expired_body',    'he', 'פינוי אחד נוסף לחשבון שלכם. מצטערים!'),
('request.expired_body',    'en', 'One extra pickup was added to your account. Sorry!'),
('request.cancel',          'he', 'ביטול בקשה'),
('request.cancel',          'en', 'Cancel request'),
('request.units_adjusted',  'he', 'המפנה עדכן את הכמות ל־{units} יחידות ({reason})'),
('request.units_adjusted',  'en', 'The picker adjusted this to {units} units ({reason})'),
('request.declined_leak',   'he', 'השקית דלפה ולא נאספה — לא חויבתם. עטפו אותה שוב ופרסמו מחדש'),
('request.declined_leak',   'en', 'The bag was leaking and wasn''t collected — you weren''t charged. Re-bag and post again'),
('request.referral_moment', 'he', 'מרוצים? חבר שמצטרף = {units} פינויים מתנה לשניכם'),
('request.referral_moment', 'en', 'Happy? A friend who joins = {units} free pickups for you both'),
('request.backstop_cta',    'he', 'שנשלח מפנה מיוחד? {price}'),
('request.backstop_cta',    'en', 'Send a dedicated picker? {price}'),
('request.approve_eta',     'he', 'המפנה יגיע בעוד ~{minutes} דק׳. מאשרים?'),
('request.approve_eta',     'en', 'Picker arrives in ~{minutes} min. Approve?'),
('request.put_out_prompt',  'he', 'שימו את השקית ליד הדלת ואשרו'),
('request.put_out_prompt',  'en', 'Put the bag outside and confirm'),
('request.bag_out_cta',     'he', 'השקית בחוץ'),
('request.bag_out_cta',     'en', 'Bag''s out'),

-- ── plan & usage / bags / meter ────────────────────────────────────────────
('usage.title',             'he', 'המנוי שלי'),
('usage.title',             'en', 'My plan'),
('usage.history',           'he', 'היסטוריית פינויים'),
('usage.history',           'en', 'Pickup history'),
('usage.order_roll',        'he', 'הזמנת גליל נוסף — {price}'),
('usage.order_roll',        'en', 'Order an extra roll — {price}'),
('bags.title',              'he', 'שקיות ובניין'),
('bags.title',              'en', 'Bags & building'),
('meter.title',             'he', 'מד הבניין'),
('meter.title',             'en', 'Building meter'),
('meter.progress',          'he', '{doors} דלתות פעילות בבניין'),
('meter.progress',          'en', '{doors} active doors in your building'),
('meter.next_tier',         'he', 'עוד {missing} דלתות — {bonus} פינויים מתנה לכולם'),
('meter.next_tier',         'en', '{missing} more doors — {bonus} free pickups for everyone'),
('meter.tier_reached',      'he', 'הבניין הגיע ל־{doors} דלתות! כולם קיבלו {bonus} פינויים'),
('meter.tier_reached',      'en', 'Your building hit {doors} doors! Everyone got {bonus} pickups'),

-- ── settings ────────────────────────────────────────────────────────────────
('settings.title',          'he', 'הגדרות'),
('settings.title',          'en', 'Settings'),
('settings.address',        'he', 'כתובת וקוד כניסה'),
('settings.address',        'en', 'Address & entry code'),
('settings.payment',        'he', 'אמצעי תשלום'),
('settings.payment',        'en', 'Payment method'),
('settings.referral',       'he', 'הקוד שלי לחברים'),
('settings.referral',       'en', 'My referral code'),
('settings.referral_share', 'he', 'שתפו את הקוד — {units} פינויים מתנה לכל צד'),
('settings.referral_share', 'en', 'Share your code — {units} free pickups each'),
('settings.pause',          'he', 'חופשה (השהיית מנוי)'),
('settings.pause',          'en', 'Vacation (pause subscription)'),
('settings.resume',         'he', 'חזרה מחופשה'),
('settings.resume',         'en', 'Resume subscription'),
('settings.confirm_first',  'he', 'אישור לפני איסוף'),
('settings.confirm_first',  'en', 'Confirm before pickup'),
('settings.confirm_first_hint', 'he', 'נבקש מכם לאשר את המפנה ולהוציא את השקית רק כשהוא בדרך'),
('settings.confirm_first_hint', 'en', 'We''ll ask you to approve the picker and put the bag out only when they''re on the way'),
('settings.language',       'he', 'שפה'),
('settings.language',       'en', 'Language'),
('settings.switch_mode',    'he', 'מעבר למצב מפנה'),
('settings.switch_mode',    'en', 'Switch to picker mode'),
('settings.switch_mode_resident', 'he', 'מעבר למצב דייר'),
('settings.switch_mode_resident', 'en', 'Switch to resident mode'),

-- ── picker onboarding ───────────────────────────────────────────────────────
('picker.onb_title',        'he', 'כמה פרטים ומתחילים להרוויח'),
('picker.onb_title',        'en', 'A few details and you start earning'),
('picker.id_number',        'he', 'תעודת זהות'),
('picker.id_number',        'en', 'ID number'),
('picker.birthdate',        'he', 'תאריך לידה'),
('picker.birthdate',        'en', 'Date of birth'),
('picker.underage',         'he', 'אפשר להצטרף רק מגיל 18'),
('picker.underage',         'en', 'You must be 18 or older to join'),
('picker.tax_status',       'he', 'סטטוס מס'),
('picker.tax_status',       'en', 'Tax status'),
('picker.tax_patur',        'he', 'עוסק פטור'),
('picker.tax_patur',        'en', 'Exempt dealer (patur)'),
('picker.tax_murshe',       'he', 'עוסק מורשה'),
('picker.tax_murshe',       'en', 'Licensed dealer (murshe)'),
('picker.tax_none',         'he', 'אין לי עוסק'),
('picker.tax_none',         'en', 'No business registration'),
('picker.poa_title',        'he', 'הסכמה לחשבונית עצמית'),
('picker.poa_title',        'en', 'Self-billing consent'),
('picker.poa_body',         'he', 'אני מאשר/ת לחברה להפיק חשבוניות עצמיות בשמי עבור התשלומים המגיעים לי'),
('picker.poa_body',         'en', 'I authorize the company to issue self-billed invoices on my behalf for amounts due to me'),
('picker.bank_details',     'he', 'פרטי חשבון לתשלום'),
('picker.bank_details',     'en', 'Bank details for payout'),
('picker.pending_verification', 'he', 'הפרטים נשלחו — נאשר אתכם בהקדם'),
('picker.pending_verification', 'en', 'Details submitted — we''ll verify you shortly'),
('training.rule1',          'he', 'רק שקיות קשורות'),
('training.rule1',          'en', 'Tied bags only'),
('training.rule2',          'he', 'עד 8 ק"ג ליחידה'),
('training.rule2',          'en', 'Up to 8kg per unit'),
('training.rule3',          'he', 'שקית דולפת? מסרבים ומצלמים'),
('training.rule3',          'en', 'Leaking bag? Decline with a photo'),
('training.rule4',          'he', 'סורקים את הברקוד ליד הפחים'),
('training.rule4',          'en', 'Scan the QR at the bins'),

-- ── picker feed / stop / collection / finish ───────────────────────────────
('feed.title',              'he', 'בקשות בסביבה'),
('feed.title',              'en', 'Requests nearby'),
('feed.available_toggle',   'he', 'זמין לאיסוף'),
('feed.available_toggle',   'en', 'Available for pickups'),
('feed.card',               'he', 'רח׳ {street} · {units} יח׳ · {payout} · {distance} מ׳ · עד {deadline}'),
('feed.card',               'en', '{street} St · {units} units · {payout} · {distance}m · by {deadline}'),
('feed.building_group',     'he', '{count} בקשות באותו בניין — איסוף אחד'),
('feed.building_group',     'en', '{count} requests in one building — a single stop'),
('feed.claim_cta',          'he', 'לקחת'),
('feed.claim_cta',          'en', 'Claim'),
('feed.already_claimed',    'he', 'נתפס — הנה הבאה'),
('feed.already_claimed',    'en', 'Taken — here''s the next one'),
('feed.empty',              'he', 'אין בקשות כרגע. נשלח התראה כשמשהו יופיע'),
('feed.empty',              'en', 'No requests right now. We''ll ping you when one appears'),

('stop.entry_code',         'he', 'קוד כניסה'),
('stop.entry_code',         'en', 'Entry code'),
('stop.code_expires',       'he', 'הקוד יוצג עוד {minutes}:{seconds}'),
('stop.code_expires',       'en', 'Code visible for {minutes}:{seconds}'),
('stop.no_code',            'he', 'אין קוד לבניין הזה — הדלת פתוחה'),
('stop.no_code',            'en', 'No code for this building — door''s open'),
('stop.deadline',           'he', 'לאסוף ולסרוק עד {time}'),
('stop.deadline',           'en', 'Collect & scan by {time}'),
('stop.navigate',           'he', 'ניווט'),
('stop.navigate',           'en', 'Navigate'),
('stop.release',            'he', 'שחרור הבקשה'),
('stop.release',            'en', 'Release this claim'),
('stop.floor_apt',          'he', 'קומה {floor} · דירה {apartment}'),
('stop.floor_apt',          'en', 'Floor {floor} · Apt {apartment}'),

('collect.title',           'he', 'איסוף'),
('collect.title',           'en', 'Collection'),
('collect.unit_check',      'he', 'יחידה {n} נאספה'),
('collect.unit_check',      'en', 'Unit {n} collected'),
('collect.chip_small',      'he', '3 קטנות = 1'),
('collect.chip_small',      'en', '3 small = 1'),
('collect.chip_oversized',  'he', 'חריגה (×2)'),
('collect.chip_oversized',  'en', 'Oversized (×2)'),
('collect.leak_cta',        'he', 'השקית דולפת — סירוב עם תמונה'),
('collect.leak_cta',        'en', 'Bag''s leaking — decline with photo'),
('collect.leak_note',       'he', 'הדייר לא יחויב ולא תקבלו נקודה שלילית'),
('collect.leak_note',       'en', 'The resident isn''t charged and you get no strike'),
('collect.done_cta',        'he', 'הכל נאסף — לסריקה בפחים'),
('collect.done_cta',        'en', 'All collected — scan at the bins'),

('finish.scan_title',       'he', 'סרקו את הברקוד שעל הפחים'),
('finish.scan_title',       'en', 'Scan the QR on the bins'),
('finish.wrong_qr',         'he', 'זה לא הברקוד של הבניין הזה'),
('finish.wrong_qr',         'en', 'That''s not this building''s QR'),
('finish.celebration',      'he', '+{amount} · סה"כ היום {total}'),
('finish.celebration',      'en', '+{amount} · today''s total {total}'),

('earnings.title',          'he', 'הרווחים שלי'),
('earnings.title',          'en', 'My earnings'),
('earnings.today',          'he', 'היום'),
('earnings.today',          'en', 'Today'),
('earnings.week',           'he', 'השבוע'),
('earnings.week',           'en', 'This week'),
('earnings.month',          'he', 'החודש'),
('earnings.month',          'en', 'This month'),
('earnings.net_hint',       'he', '{net} נטו ליחידה'),
('earnings.net_hint',       'en', '{net} net per unit'),
('earnings.payout_schedule','he', 'תשלום כל יום ראשון'),
('earnings.payout_schedule','en', 'Paid out every Sunday'),
('earnings.invoices',       'he', 'חשבוניות'),
('earnings.invoices',       'en', 'Invoices'),
('earnings.strikes',        'he', 'נקודות שליליות: {count}/{max}'),
('earnings.strikes',        'en', 'Strikes: {count}/{max}'),

-- ── push templates ──────────────────────────────────────────────────────────
('push.requests_nearby.title', 'he', '{count} בקשות לידך'),
('push.requests_nearby.title', 'en', '{count} requests near you'),
('push.requests_nearby.body',  'he', 'אפשר להרוויח {amount} עכשיו'),
('push.requests_nearby.body',  'en', 'Earn {amount} right now'),
('push.request_claimed.title', 'he', 'מישהו בדרך לשקית שלך'),
('push.request_claimed.title', 'en', 'Someone''s coming for your bag'),
('push.request_claimed.body',  'he', 'האיסוף יקרה עד {deadline}'),
('push.request_claimed.body',  'en', 'Pickup by {deadline}'),
('push.request_done.title',    'he', 'השקית בפחים ✓'),
('push.request_done.title',    'en', 'Bag''s in the bins ✓'),
('push.request_done.body',     'he', 'תודה שאתם איתנו'),
('push.request_done.body',     'en', 'Thanks for being with us'),
('push.request_expired.title', 'he', 'לא הספקנו — קיבלתם זיכוי'),
('push.request_expired.title', 'en', 'We missed it — you got a credit'),
('push.request_expired.body',  'he', 'פינוי נוסף חינם נוסף לחשבונכם'),
('push.request_expired.body',  'en', 'A free extra pickup was added to your account'),
('push.request_leak.title',    'he', 'השקית לא נאספה — היא דולפת'),
('push.request_leak.title',    'en', 'Bag not collected — it''s leaking'),
('push.request_leak.body',     'he', 'לא חויבתם. עטפו שוב ופרסמו מחדש'),
('push.request_leak.body',     'en', 'You weren''t charged. Re-bag and post again'),
('push.units_adjusted.title',  'he', 'עדכון כמות בפינוי'),
('push.units_adjusted.title',  'en', 'Pickup quantity updated'),
('push.units_adjusted.body',   'he', 'הכמות עודכנה ל־{units} יחידות'),
('push.units_adjusted.body',   'en', 'Updated to {units} units'),
('push.approve_eta.title',     'he', 'מפנה מוכן לצאת אליכם'),
('push.approve_eta.title',     'en', 'A picker is ready to head over'),
('push.approve_eta.body',      'he', 'אשרו את האיסוף בישומון'),
('push.approve_eta.body',      'en', 'Approve the pickup in the app'),
('push.put_out.title',         'he', 'המפנה בדרך — הוציאו את השקית'),
('push.put_out.title',         'en', 'Picker''s on the way — put the bag out'),
('push.put_out.body',          'he', 'אשרו בישומון כשהשקית בחוץ'),
('push.put_out.body',          'en', 'Confirm in the app once it''s outside'),
('push.claim_lapsed.title',    'he', 'האיסוף לא הושלם בזמן'),
('push.claim_lapsed.title',    'en', 'Pickup wasn''t completed in time'),
('push.claim_lapsed.body',     'he', 'הבקשה חזרה ללוח וקיבלתם נקודה שלילית'),
('push.claim_lapsed.body',     'en', 'The request was reposted and you received a strike'),
('push.picker_suspended.title','he', 'החשבון הושהה'),
('push.picker_suspended.title','en', 'Account suspended'),
('push.picker_suspended.body', 'he', 'הצטברו {count} נקודות שליליות. צרו קשר לבירור'),
('push.picker_suspended.body', 'en', '{count} strikes accumulated. Contact us to review'),
('push.referral_reward.title', 'he', 'קיבלתם {units} פינויים מתנה 🎁'),
('push.referral_reward.title', 'en', 'You got {units} free pickups 🎁'),
('push.referral_reward.body',  'he', 'תודה שהמלצתם עלינו'),
('push.referral_reward.body',  'en', 'Thanks for spreading the word'),
('push.meter_tier.title',      'he', 'הבניין שלכם שובר שיאים 🏢'),
('push.meter_tier.title',      'en', 'Your building is on a roll 🏢'),
('push.meter_tier.body',       'he', '{doors} דלתות פעילות — כולם קיבלו {bonus} פינויים'),
('push.meter_tier.body',       'en', '{doors} active doors — everyone got {bonus} pickups'),
('push.payout_sent.title',     'he', 'התשלום השבועי יצא 💸'),
('push.payout_sent.title',     'en', 'Weekly payout sent 💸'),
('push.payout_sent.body',      'he', '{amount} בדרך לחשבון שלך'),
('push.payout_sent.body',      'en', '{amount} on its way to your account'),

-- ── common ──────────────────────────────────────────────────────────────────
('common.continue',              'he', 'המשך'),
('common.continue',              'en', 'Continue'),
('auth.send_cta',                'he', 'שלחו לי קוד'),
('auth.send_cta',                'en', 'Send me a code'),
('plan.change_title',            'he', 'תנאי המסלול עודכנו'),
('plan.change_title',            'en', 'Your plan terms were updated'),
('plan.change_cta',              'he', 'אישור המעבר לתנאים החדשים'),
('plan.change_cta',              'en', 'Accept the new terms'),

('request.approve_cta',          'he', 'מאשרים'),
('request.approve_cta',          'en', 'Approve'),
('request.decline_cta',          'he', 'לא מתאים עכשיו'),
('request.decline_cta',          'en', 'Not now'),
('picker.vat_id',                'he', 'מספר עוסק מורשה'),
('picker.vat_id',                'en', 'VAT number'),
('picker.bank',                  'he', 'בנק'),
('picker.bank',                  'en', 'Bank'),
('picker.branch',                'he', 'סניף'),
('picker.branch',                'en', 'Branch'),
('picker.account',               'he', 'מספר חשבון'),
('picker.account',               'en', 'Account number'),
('picker.rejected',              'he', 'הבקשה להצטרף לא אושרה'),
('picker.rejected',              'en', 'Your application was not approved'),
('stop.title',                   'he', 'העצירה שלי'),
('stop.title',                   'en', 'My stop'),
('stop.empty',                   'he', 'אין עצירה פעילה — קחו בקשה מהפיד'),
('stop.empty',                   'en', 'No active stop — claim one from the feed'),
('stop.waiting_resident',        'he', 'ממתינים לאישור הדייר'),
('stop.waiting_resident',        'en', 'Waiting for the resident'),
('collect.chip_large',           'he', 'שקיות גדולות'),
('collect.chip_large',           'en', 'Large bags'),
('collect.chip_overweight',      'he', 'קבוצת הקטנות כבדה מדי'),
('collect.chip_overweight',      'en', 'Small-bag group over the weight cap'),
('common.camera_permission',     'he', 'צריך הרשאת מצלמה כדי להמשיך'),
('common.camera_permission',     'en', 'Camera permission is needed to continue'),

-- ── sms ─────────────────────────────────────────────────────────────────────
('sms.otp_body',                 'he', 'קוד הכניסה שלך לפינוי+: {otp}'),
('sms.otp_body',                 'en', 'Your Pinui+ sign-in code: {otp}'),
('picker.coming_soon',           'he', 'מצב מפנה בדרך — ממש בקרוב'),
('picker.coming_soon',           'en', 'Picker mode is coming — very soon'),

-- ── self-billed invoice + QR poster (rendered server/admin side) ───────────
('invoice.title',                'he', 'חשבונית עצמית (Self-Billed)'),
('invoice.title',                'en', 'Self-Billed Invoice'),
('invoice.issued_note',          'he', 'הופקה מכוח ייפוי כוח לחיוב עצמי'),
('invoice.issued_note',          'en', 'Issued under a self-billing power of attorney'),
('invoice.supplier',             'he', 'ספק'),
('invoice.supplier',             'en', 'Supplier'),
('invoice.vat_dealer',           'he', 'עוסק {vat_id}'),
('invoice.vat_dealer',           'en', 'Dealer no. {vat_id}'),
('invoice.col_item',             'he', 'פירוט'),
('invoice.col_item',             'en', 'Item'),
('invoice.col_amount',           'he', 'סכום'),
('invoice.col_amount',           'en', 'Amount'),
('invoice.line_pickups',         'he', 'איסוף ופינוי — {units} יחידות'),
('invoice.line_pickups',         'en', 'Collection & disposal — {units} units'),
('invoice.vat_label',            'he', 'מע"מ ({pct}%)'),
('invoice.vat_label',            'en', 'VAT ({pct}%)'),
('invoice.total_due',            'he', 'סה"כ לתשלום'),
('invoice.total_due',            'en', 'Total due'),
('invoice.print_hint',           'he', 'להפקת PDF: הדפסה ← שמירה כ-PDF'),
('invoice.print_hint',           'en', 'For a PDF: Print → Save as PDF'),
('invoice.masav_header',         'he', 'PINUI PAYOUTS'),
('invoice.masav_header',         'en', 'PINUI PAYOUTS'),
('qr_poster.scan_hint',          'he', 'סרקו כאן בסיום הפינוי'),
('qr_poster.scan_hint',          'en', 'Scan here when the pickup is done'),

-- ── errors (stable RPC codes → copy) ───────────────────────────────────────
('error.already_claimed',        'he', 'הבקשה כבר נתפסה'),
('error.already_claimed',        'en', 'This request was already claimed'),
('error.insufficient_allowance', 'he', 'נגמרו הפינויים החודש'),
('error.insufficient_allowance', 'en', 'No pickups left this month'),
('error.illegal_transition',     'he', 'הפעולה לא אפשרית במצב הנוכחי'),
('error.illegal_transition',     'en', 'That action isn''t possible right now'),
('error.claim_expired',          'he', 'זמן האיסוף עבר'),
('error.claim_expired',          'en', 'The pickup window has passed'),
('error.claim_limit_reached',    'he', 'סיימו את האיסוף הנוכחי לפני שלוקחים חדש'),
('error.claim_limit_reached',    'en', 'Finish your current pickup before claiming another'),
('error.building_paused',        'he', 'השירות בבניין הזה מושהה זמנית'),
('error.building_paused',        'en', 'Service in this building is temporarily paused'),
('error.service_disabled',       'he', 'השירות מושהה זמנית — חוזרים ממש בקרוב'),
('error.service_disabled',       'en', 'Service is temporarily paused — back very soon'),
('error.not_authorized',         'he', 'אין הרשאה לפעולה הזו'),
('error.not_authorized',         'en', 'You''re not authorized to do that'),
('error.not_found',              'he', 'לא נמצא'),
('error.not_found',              'en', 'Not found'),
('error.picker_not_active',      'he', 'החשבון עדיין לא אושר לאיסוף'),
('error.picker_not_active',      'en', 'Your account isn''t approved for pickups yet'),
('error.picker_suspended',       'he', 'החשבון מושהה'),
('error.picker_suspended',       'en', 'Your account is suspended'),
('error.rate_limited',           'he', 'יותר מדי ניסיונות — נסו שוב עוד רגע'),
('error.rate_limited',           'en', 'Too many attempts — try again in a moment'),
('error.invalid_qr',             'he', 'זה לא הברקוד של הבניין הזה'),
('error.invalid_qr',             'en', 'That''s not this building''s QR code'),
('error.photo_required',         'he', 'חובה לצרף תמונה'),
('error.photo_required',         'en', 'A photo is required'),
('error.underage',               'he', 'אפשר להצטרף רק מגיל 18'),
('error.underage',               'en', 'You must be 18 or older'),
('error.invalid_units',          'he', 'כמות יחידות לא תקינה'),
('error.invalid_units',          'en', 'Invalid number of units'),
('error.ttl_passed',             'he', 'מועד היעד הזה כבר עבר להיום — בחרו מועד אחר'),
('error.ttl_passed',             'en', 'That deadline already passed today — pick another'),
('error.subscription_not_active','he', 'אין מנוי פעיל'),
('error.subscription_not_active','en', 'No active subscription'),
('error.feature_disabled',       'he', 'האפשרות הזו לא זמינה כרגע'),
('error.feature_disabled',       'en', 'This option isn''t available right now'),
('error.config_validation_failed','he', 'ערך לא תקין להגדרה הזו'),
('error.config_validation_failed','en', 'Invalid value for this setting'),
('error.unknown',                'he', 'משהו השתבש — נסו שוב'),
('error.unknown',                'en', 'Something went wrong — try again')

on conflict (key, locale) do nothing;
