-- All user-facing copy (he primary, en fallback) — the LEMATA design language
-- (canvas: "Lemata App UI"). Admin-editable via the strings editor
-- (api.admin_set_string). Push templates use {placeholders} resolved by the
-- notify-worker at send time. Terminology: pickers are שליחים, allowance
-- units are שקיות, the brand is למטה ("down") — the bag goes down.
insert into public.strings (key, locale, value) values

-- ── app ─────────────────────────────────────────────────────────────────────
('app_name',                'he', 'למטה'),
('app_name',                'en', 'Lemata'),

-- ── auth / onboarding (resident) ───────────────────────────────────────────
('auth.phone_title',        'he', 'השקית מחכה בחוץ? מכאן זה עלינו.'),
('auth.phone_title',        'en', 'Bag waiting outside? We take it from here.'),
('auth.phone_label',        'he', 'נייד'),
('auth.phone_label',        'en', 'Mobile'),
('auth.otp_title',          'he', 'הקוד מה־SMS'),
('auth.otp_title',          'en', 'The code from the SMS'),
('auth.otp_resend',         'he', 'שליחה חוזרת בעוד {seconds}'),
('auth.otp_resend',         'en', 'Resend in {seconds}'),
('auth.otp_resend_now',     'he', 'שליחה חוזרת'),
('auth.otp_resend_now',     'en', 'Resend code'),
('auth.send_cta',           'he', 'ממשיכים'),
('auth.send_cta',           'en', 'Continue'),
('auth.terms_note',         'he', 'בהמשך מאשרים את תנאי השימוש והפרטיות'),
('auth.terms_note',         'en', 'You''ll approve the terms & privacy later on'),
('auth.mode_title',         'he', 'איך תרצו להשתמש בלמטה?'),
('auth.mode_title',         'en', 'How would you like to use Lemata?'),
('auth.mode_resident',      'he', 'שקית ליד הדלת — מישהו כבר ייקח אותה למטה'),
('auth.mode_resident',      'en', 'Bag by the door — someone takes it down'),
('auth.mode_picker',        'he', 'אני ממילא יורד — שווה שארוויח על הדרך'),
('auth.mode_picker',        'en', 'I''m going down anyway — might as well earn'),

('onboarding.address_title','he', 'לאן מגיעים?'),
('onboarding.address_title','en', 'Where do we come to?'),
('onboarding.address_sub',  'he', 'מהדלת שלכם — לפחים של הבניין. זהו המסלול.'),
('onboarding.address_sub',  'en', 'From your door to the building bins. That''s the whole route.'),
('onboarding.city',         'he', 'עיר'),
('onboarding.city',         'en', 'City'),
('onboarding.street',       'he', 'רחוב'),
('onboarding.street',       'en', 'Street'),
('onboarding.house_number', 'he', 'מספר בית'),
('onboarding.house_number', 'en', 'House number'),
('onboarding.floor',        'he', 'קומה'),
('onboarding.floor',        'en', 'Floor'),
('onboarding.apartment',    'he', 'דירה'),
('onboarding.apartment',    'en', 'Apartment'),
('onboarding.entry_code_title', 'he', 'קוד הכניסה לבניין'),
('onboarding.entry_code_title', 'en', 'Building entry code'),
('onboarding.entry_code_sub',   'he', 'כדי שהשליח יגיע לפחים — לא לדלת שלכם.'),
('onboarding.entry_code_sub',   'en', 'So the courier reaches the bins — not your door.'),
('onboarding.no_code',      'he', 'אין קוד בבניין? ממשיכים בלי'),
('onboarding.no_code',      'en', 'No code in your building? Continue without'),
('onboarding.save_cta',     'he', 'שומרים ומסיימים'),
('onboarding.save_cta',     'en', 'Save & finish'),
('onboarding.door_note',    'he', 'איך מזהים את הדלת? (לא חובה)'),
('onboarding.door_note',    'en', 'How to spot your door (optional)'),

('trust.title',             'he', 'רגע האמון'),
('trust.title',             'en', 'The trust moment'),
('trust.encrypted',         'he', 'הקוד מוצפן מקצה לקצה'),
('trust.encrypted',         'en', 'The code is encrypted end to end'),
('trust.timeboxed',         'he', 'נחשף לשליח מאומת בלבד, לזמן קצוב — {minutes} דקות לחשיפה'),
('trust.timeboxed',         'en', 'Revealed only to a verified courier, time-boxed — {minutes} minutes per reveal'),
('trust.audited',           'he', 'כל חשיפה מתועדת ביומן'),
('trust.audited',           'en', 'Every reveal is logged'),

-- ── plan picker ─────────────────────────────────────────────────────────────
('plan.title',              'he', 'כמה אתם זורקים?'),
('plan.title',              'en', 'How much do you throw out?'),
('plan.subtitle',           'he', 'שתי שאלות — והמלצה אחת, כבר מסומנת.'),
('plan.subtitle',           'en', 'Two questions — one recommendation, already selected.'),
('plan.q_household',        'he', 'נפשות בבית'),
('plan.q_household',        'en', 'People at home'),
('plan.q_bags_week',        'he', 'שקיות בשבוע'),
('plan.q_bags_week',        'en', 'Bags a week'),
('plan.q_format',           'he', 'איזה גודל שקית נוח לכם?'),
('plan.q_format',           'en', 'Which bag size suits you?'),
('plan.format_large',       'he', 'גדולות (רגילות)'),
('plan.format_large',       'en', 'Large (regular)'),
('plan.format_small',       'he', 'קטנות (עד 3 = שקית אחת במכסה)'),
('plan.format_small',       'en', 'Small (up to 3 = one bag of quota)'),
('plan.recommended',        'he', 'מומלץ לכם'),
('plan.recommended',        'en', 'Recommended for you'),
('plan.S.name',             'he', 'קטן'),
('plan.S.name',             'en', 'Small'),
('plan.M.name',             'he', 'בינוני'),
('plan.M.name',             'en', 'Medium'),
('plan.L.name',             'he', 'גדול'),
('plan.L.name',             'en', 'Large'),
('plan.per_month',          'he', 'בחודש'),
('plan.per_month',          'en', '/month'),
('plan.units_included',     'he', '{units} שקיות בחודש'),
('plan.units_included',     'en', '{units} bags a month'),
('plan.bags_included',      'he', '✓ כולל שקיות עד הבית'),
('plan.bags_included',      'en', '✓ Bags delivered — included'),
('plan.no_rollover',        'he', 'שקיות שלא נוצלו אינן נצברות'),
('plan.no_rollover',        'en', 'Unused bags don''t roll over'),
('plan.pay_cta',            'he', 'מתחילים · {price} בחודש'),
('plan.pay_cta',            'en', 'Start · {price}/month'),
('plan.pay_note',           'he', 'תשלום בהקשה אחת · ביטול מתי שרוצים'),
('plan.pay_note',           'en', 'One-tap payment · cancel anytime'),
('plan.upgrade_title',      'he', 'נגמרה המכסה החודש'),
('plan.upgrade_title',      'en', 'You''re out of bags this month'),
('plan.upgrade_body',       'he', 'שדרגו — יוצא זול יותר לשקית:'),
('plan.upgrade_body',       'en', 'Upgrade — it''s cheaper per bag:'),
('plan.upgrade_cta',        'he', 'לשדרג עכשיו'),
('plan.upgrade_cta',        'en', 'Upgrade now'),
('plan.price_per_unit',     'he', '{price} לשקית'),
('plan.price_per_unit',     'en', '{price} per bag'),
('plan.change_title',       'he', 'תנאי המסלול עודכנו'),
('plan.change_title',       'en', 'Your plan terms were updated'),
('plan.change_cta',         'he', 'אישור המעבר לתנאים החדשים'),
('plan.change_cta',         'en', 'Accept the new terms'),

-- ── resident HOME ───────────────────────────────────────────────────────────
('home.big_button',         'he', 'השקית מוכנה'),
('home.big_button',         'en', 'Bag''s ready'),
('home.big_button_hint',    'he', 'בחוץ ליד הדלת? זה הכול'),
('home.big_button_hint',    'en', 'Outside your door? That''s all'),
('home.active_sub',         'he', 'מנוי פעיל'),
('home.active_sub',         'en', 'Active plan'),
('home.allowance_left',     'he', 'שקיות נשארו החודש'),
('home.allowance_left',     'en', 'bags left this month'),
('home.credits_left',       'he', '+{units} זיכויים'),
('home.credits_left',       'en', '+{units} credits'),
('home.building_strip',     'he', '{doors} שכנים בבניין שלך'),
('home.building_strip',     'en', '{doors} neighbors in your building'),
('home.tab',                'he', 'בית'),
('home.tab',                'en', 'Home'),

-- ── submit sheet ────────────────────────────────────────────────────────────
('submit.title',            'he', 'השקית בחוץ ליד הדלת?'),
('submit.title',            'en', 'Is the bag outside your door?'),
('submit.subtitle',         'he', 'מעולה. מכאן זה עלינו — הבקשה מתפרסמת לשכונה.'),
('submit.subtitle',         'en', 'Great. From here it''s on us — the request goes out to the neighborhood.'),
('submit.deadline_label',   'he', 'עד מתי לאסוף?'),
('submit.deadline_label',   'en', 'Pick up by when?'),
('submit.units_label',      'he', 'כמה שקיות?'),
('submit.units_label',      'en', 'How many bags?'),
('submit.unit_hint',        'he', 'שקית גדולה אחת או עד 3 קטנות = שקית אחת מהמכסה'),
('submit.unit_hint',        'en', 'One large bag or up to 3 small = one bag of quota'),
('submit.cta',              'he', 'לפרסם בקשה'),
('submit.cta',              'en', 'Post request'),
('submit.success',          'he', 'סגרנו — נאסוף היום'),
('submit.success',          'en', 'Done — we''ll collect today'),
('submit.cancel_hint',      'he', 'אפשר לבטל חינם עד שהשקית נתפסת'),
('submit.cancel_hint',      'en', 'Free to cancel until it''s claimed'),
('ttl.noon',                'he', 'עד הצהריים'),
('ttl.noon',                'en', 'By noon'),
('ttl.evening',             'he', 'עד 18:00'),
('ttl.evening',             'en', 'By 6pm'),
('ttl.today',               'he', 'היום'),
('ttl.today',               'en', 'Today'),

-- ── active request card ─────────────────────────────────────────────────────
('request.out_status',      'he', 'השקית בחוץ · תיאסף עד {time}'),
('request.out_status',      'en', 'Bag''s out · collected by {time}'),
('request.waiting',         'he', 'נעדכן ברגע שמישהו תופס · אין מה לעשות בינתיים'),
('request.waiting',         'en', 'We''ll ping you the moment it''s claimed · nothing to do meanwhile'),
('request.waiting_note',    'he', 'לא נאספה עד אז? שקית זיכוי, אוטומטית.'),
('request.waiting_note',    'en', 'Not collected by then? A credit bag, automatically.'),
('request.claimed',         'he', 'השקית בדרך למטה 🎉'),
('request.claimed',         'en', 'The bag''s on its way down 🎉'),
('request.claimed_note',    'he', 'אין צורך בכלום — רק שהשקית תחכה בחוץ'),
('request.claimed_note',    'en', 'Nothing needed — just leave the bag outside'),
('request.verified_courier','he', 'שליח מאומת'),
('request.verified_courier','en', 'Verified courier'),
('request.collected',       'he', 'נאספה ✓'),
('request.collected',       'en', 'Collected ✓'),
('request.done_title',      'he', 'נאספה ונסרקה בפח הבניין ✓'),
('request.done_title',      'en', 'Collected & scanned at the building bins ✓'),
('request.done_note',       'he', 'הבקשה נסגרה · אפשר לשגר עוד אחת מתי שרוצים'),
('request.done_note',       'en', 'Request closed · post another whenever you like'),
('request.expired_title',   'he', 'לא הסתדר היום.'),
('request.expired_title',   'en', 'Didn''t work out today.'),
('request.expired_body',    'he', 'אף אחד לא ירד הפעם — זה עלינו, לא עליכם. קיבלתם שקית זיכוי.'),
('request.expired_body',    'en', 'Nobody came down this time — that''s on us, not you. You got a credit bag.'),
('request.expired_retry',   'he', 'ננסה שוב מחר · השקית יכולה להישאר בחוץ · בלי קנסות, בלי אשמה'),
('request.expired_retry',   'en', 'We''ll try again tomorrow · the bag can stay out · no fines, no guilt'),
('request.cancel',          'he', 'ביטול הבקשה'),
('request.cancel',          'en', 'Cancel request'),
('request.units_adjusted',  'he', 'השליח עדכן את הכמות ל־{units} שקיות'),
('request.units_adjusted',  'en', 'The courier adjusted this to {units} bags'),
('request.declined_leak',   'he', 'השקית דלפה ולא נאספה — לא חויבתם. עטפו שוב ופרסמו מחדש'),
('request.declined_leak',   'en', 'The bag was leaking and wasn''t collected — you weren''t charged. Re-bag and post again'),
('request.referral_moment', 'he', 'שכנים שיאהבו את זה? כל שכן שמצטרף — שקית מתנה לשניכם'),
('request.referral_moment', 'en', 'Neighbors who''d love this? Each one who joins = a free bag for you both'),
('request.referral_cta',    'he', 'שלחו קוד'),
('request.referral_cta',    'en', 'Share code'),
('request.backstop_cta',    'he', 'שלחו מישהו עכשיו · {price}'),
('request.backstop_cta',    'en', 'Send someone now · {price}'),
('request.backstop_hint',   'he', 'שליח ייעודי בתשלום, בדרך כלל תוך שעה'),
('request.backstop_hint',   'en', 'A paid dedicated courier, usually within the hour'),
('request.approve_eta',     'he', 'שליח מוכן לרדת אליכם בעוד ~{minutes} דק׳. מאשרים?'),
('request.approve_eta',     'en', 'A courier is ready in ~{minutes} min. Approve?'),
('request.approve_cta',     'he', 'מאשרים'),
('request.approve_cta',     'en', 'Approve'),
('request.decline_cta',     'he', 'לא מתאים עכשיו'),
('request.decline_cta',     'en', 'Not now'),
('request.put_out_prompt',  'he', 'שימו את השקית ליד הדלת ואשרו'),
('request.put_out_prompt',  'en', 'Put the bag outside and confirm'),
('request.bag_out_cta',     'he', 'השקית בחוץ'),
('request.bag_out_cta',     'en', 'Bag''s out'),

-- ── status pills (shared) ───────────────────────────────────────────────────
('pill.out',                'he', '● בחוץ'),
('pill.out',                'en', '● Out'),
('pill.claimed',            'he', '● נתפסה'),
('pill.claimed',            'en', '● Claimed'),
('pill.collected',          'he', '✓ נאספה'),
('pill.collected',          'en', '✓ Collected'),
('pill.credit',             'he', '+1 זיכוי'),
('pill.credit',             'en', '+1 credit'),
('pill.waiting_resident',   'he', 'ממתין לאישור דייר'),
('pill.waiting_resident',   'en', 'Waiting for resident'),
('pill.open',               'he', '● פתוחה'),
('pill.open',               'en', '● Open'),
('pill.mine',               'he', '● שלי'),
('pill.mine',               'en', '● Mine'),
('pill.paid',               'he', '✓ שולם'),
('pill.paid',               'en', '✓ Paid'),

-- ── plan & usage / bags / meter ────────────────────────────────────────────
('usage.title',             'he', 'שימוש'),
('usage.title',             'en', 'Usage'),
('usage.left_single',       'he', 'נשארה שקית אחת'),
('usage.left_single',       'en', 'One bag left'),
('usage.left_many',         'he', 'נשארו {units} שקיות'),
('usage.left_many',         'en', '{units} bags left'),
('usage.resets_at',         'he', 'המכסה מתחדשת ב־{date} · זיכויים נשמרים'),
('usage.resets_at',         'en', 'Quota renews on {date} · credits are kept'),
('usage.history',           'he', 'החודש'),
('usage.history',           'en', 'This month'),
('usage.history_line',      'he', '{units} שקיות · {street}'),
('usage.history_line',      'en', '{units} bags · {street}'),
('usage.order_roll',        'he', 'גליל שקיות נוסף — {price}'),
('usage.order_roll',        'en', 'Extra bag roll — {price}'),
('usage.order_roll_note',   'he', 'מגיע עם האיסוף הבא — בלי משלוח נפרד'),
('usage.order_roll_note',   'en', 'Arrives with your next pickup — no separate delivery'),
('usage.tab',               'he', 'שימוש'),
('usage.tab',               'en', 'Usage'),
('bags.title',              'he', 'השקיות שלך'),
('bags.title',              'en', 'Your bags'),
('bags.next_roll',          'he', 'הגליל הבא בדרך — עם האיסוף הקרוב'),
('bags.next_roll',          'en', 'Next roll on its way — with your next pickup'),
('bags.left_in_roll',       'he', 'נשארו {count} שקיות בגליל'),
('bags.left_in_roll',       'en', '{count} bags left in the roll'),
('bags.rules_title',        'he', 'מה נחשבת שקית'),
('bags.rules_title',        'en', 'What counts as a bag'),
('bags.rule_tied',          'he', 'קשורה היטב — פתוחה נשארת בחוץ'),
('bags.rule_tied',          'en', 'Tied well — an open one stays out'),
('bags.rule_weight',        'he', 'עד {kg} ק״ג'),
('bags.rule_weight',        'en', 'Up to {kg} kg'),
('bags.rule_oversized',     'he', 'גדולה במיוחד? נספרת כ־{mult}'),
('bags.rule_oversized',     'en', 'Extra large? Counts as {mult}'),
('bags.rule_leak',          'he', 'דולפת? השליח מצלם ומדלג — בלי דרמה, תקבלו עדכון ותוכלו לארוז מחדש'),
('bags.rule_leak',          'en', 'Leaking? The courier photographs and skips — no drama, you''ll get an update and can re-bag'),
('bags.tab',                'he', 'שקיות'),
('bags.tab',                'en', 'Bags'),
('invite.tab',              'he', 'הזמינו'),
('invite.tab',              'en', 'Invite'),
('invite.have_code',        'he', 'קיבלתם קוד משכן?'),
('invite.have_code',        'en', 'Got a neighbor''s code?'),
('invite.code_placeholder', 'he', 'PN-XXXXXX'),
('invite.code_placeholder', 'en', 'PN-XXXXXX'),
('invite.apply_cta',        'he', 'הפעלה'),
('invite.apply_cta',        'en', 'Apply'),
('invite.applied',          'he', 'הקוד נקלט — השקיות יגיעו אחרי התשלום הראשון 🎁'),
('invite.applied',          'en', 'Code applied — the bags arrive after your first payment 🎁'),
('meter.title',             'he', 'הבניין שלכם'),
('meter.title',             'en', 'Your building'),
('meter.progress',          'he', '{doors} דלתות בבניין'),
('meter.progress',          'en', '{doors} doors in your building'),
('meter.next_tier',         'he', 'עוד {missing} — {bonus} שקיות מתנה לכולם'),
('meter.next_tier',         'en', '{missing} more — {bonus} free bags for everyone'),
('meter.tier_reached',      'he', 'הבניין הגיע ל־{doors} דלתות! כולם קיבלו {bonus} שקיות'),
('meter.tier_reached',      'en', 'Your building hit {doors} doors! Everyone got {bonus} bags'),
('meter.disclaimer',        'he', 'בונוסים הם תמיד שקיות — השירות זהה בכל בניין'),
('meter.disclaimer',        'en', 'Bonuses are always bags — service is identical in every building'),
('meter.invite_cta',        'he', 'הזמינו את השכנים'),
('meter.invite_cta',        'en', 'Invite your neighbors'),

-- ── settings ────────────────────────────────────────────────────────────────
('settings.title',          'he', 'הגדרות'),
('settings.title',          'en', 'Settings'),
('settings.address',        'he', 'כתובת'),
('settings.address',        'en', 'Address'),
('settings.entry_code',     'he', 'קוד הבניין'),
('settings.entry_code',     'en', 'Building code'),
('settings.entry_code_note','he', 'מוצפן · כל חשיפה מתועדת'),
('settings.entry_code_note','en', 'Encrypted · every reveal is logged'),
('settings.payment',        'he', 'תשלום'),
('settings.payment',        'en', 'Payment'),
('settings.referral',       'he', 'קוד הזמנה'),
('settings.referral',       'en', 'Invite code'),
('settings.referral_share', 'he', 'כל שכן שמצטרף — {units} שקיות מתנה לכל צד'),
('settings.referral_share', 'en', 'Each neighbor who joins — {units} free bags for each side'),
('settings.share_cta',      'he', 'שיתוף'),
('settings.share_cta',      'en', 'Share'),
('settings.pause',          'he', 'מצב חופשה'),
('settings.pause',          'en', 'Vacation mode'),
('settings.pause_note',     'he', 'משהים חיובים, שומרים יתרה'),
('settings.pause_note',     'en', 'Billing paused, balance kept'),
('settings.resume',         'he', 'חזרה מחופשה'),
('settings.resume',         'en', 'Resume'),
('settings.confirm_first',  'he', 'לשים את השקית רק אחרי אישור שליח'),
('settings.confirm_first',  'en', 'Put the bag out only after courier approval'),
('settings.confirm_first_hint', 'he', 'כבוי כברירת מחדל — פשוט שמים בחוץ. הפעלה מחזירה שלב אישור, רק אצלכם.'),
('settings.confirm_first_hint', 'en', 'Off by default — just put it out. Turning on adds an approval step, only for you.'),
('settings.language',       'he', 'שפה'),
('settings.language',       'en', 'Language'),
('settings.language_note',  'he', 'עברית · English'),
('settings.language_note',  'en', 'עברית · English'),
('settings.sign_out',       'he', 'התנתקות'),
('settings.sign_out',       'en', 'Sign out'),
('settings.switch_mode',    'he', 'מעבר למצב שליחים'),
('settings.switch_mode',    'en', 'Switch to courier mode'),
('settings.switch_mode_resident', 'he', 'מעבר למצב דיירים'),
('settings.switch_mode_resident', 'en', 'Switch to resident mode'),

-- ── picker (שליח) onboarding ───────────────────────────────────────────────
('picker.onb_title',        'he', 'קליטה מהירה — פחות מ־3 דקות. מבטיחים.'),
('picker.onb_title',        'en', 'Quick onboarding — under 3 minutes. Promise.'),
('picker.phone_verified',   'he', '✓ טלפון אומת'),
('picker.phone_verified',   'en', '✓ Phone verified'),
('picker.id_step',          'he', 'ת״ז + גיל 18'),
('picker.id_step',          'en', 'ID + 18+'),
('picker.id_number',        'he', 'תעודת זהות'),
('picker.id_number',        'en', 'ID number'),
('picker.birthdate',        'he', 'תאריך לידה'),
('picker.birthdate',        'en', 'Date of birth'),
('picker.underage',         'he', 'אפשר להצטרף רק מגיל 18'),
('picker.underage',         'en', 'You must be 18 or older to join'),
('picker.tax_status',       'he', 'מעמד מס'),
('picker.tax_status',       'en', 'Tax status'),
('picker.tax_sub',          'he', 'בוחרים פעם אחת — אנחנו מסדרים את הניירת.'),
('picker.tax_sub',          'en', 'Choose once — we handle the paperwork.'),
('picker.tax_patur',        'he', 'עוסק פטור'),
('picker.tax_patur',        'en', 'Exempt dealer (patur)'),
('picker.tax_murshe',       'he', 'עוסק מורשה'),
('picker.tax_murshe',       'en', 'Licensed dealer (murshe)'),
('picker.tax_none',         'he', 'אין לי עסק'),
('picker.tax_none',         'en', 'No business'),
('picker.tax_none_hint',    'he', 'הרוב מתחילים כאן'),
('picker.tax_none_hint',    'en', 'Most start here'),
('picker.vat_id',           'he', 'מספר עוסק מורשה'),
('picker.vat_id',           'en', 'VAT number'),
('picker.poa_title',        'he', 'אנחנו מפיקים חשבוניות בשבילך'),
('picker.poa_title',        'en', 'We issue your invoices for you'),
('picker.poa_body',         'he', 'חשבונית עצמית על כל תשלום, אוטומטית. בלי רו״ח, בלי טפסים.'),
('picker.poa_body',         'en', 'A self-billed invoice for every payout, automatically. No accountant, no forms.'),
('picker.poa_consent',      'he', 'מאשר/ת הפקת חשבונית עצמית בשמי'),
('picker.poa_consent',      'en', 'I authorize self-billed invoices in my name'),
('picker.to_bank_cta',      'he', 'ממשיכים לפרטי תשלום'),
('picker.to_bank_cta',      'en', 'Continue to payout details'),
('picker.bank_details',     'he', 'פרטי חשבון לתשלום'),
('picker.bank_details',     'en', 'Bank details for payout'),
('picker.bank',             'he', 'בנק'),
('picker.bank',             'en', 'Bank'),
('picker.branch',           'he', 'סניף'),
('picker.branch',           'en', 'Branch'),
('picker.account',          'he', 'מספר חשבון'),
('picker.account',          'en', 'Account number'),
('picker.pending_verification', 'he', 'הפרטים נשלחו — נאשר אתכם בהקדם'),
('picker.pending_verification', 'en', 'Details submitted — we''ll verify you shortly'),
('picker.rejected',         'he', 'הבקשה להצטרף לא אושרה'),
('picker.rejected',         'en', 'Your application was not approved'),
('picker.coming_soon',      'he', 'מצב שליחים בדרך — ממש בקרוב'),
('picker.coming_soon',      'en', 'Courier mode is coming — very soon'),
('training.title',          'he', '4 כללים. זהו.'),
('training.title',          'en', '4 rules. That''s it.'),
('training.rule1',          'he', 'קשורה בלבד'),
('training.rule1',          'en', 'Tied only'),
('training.rule1_sub',      'he', 'שקית פתוחה נשארת על הרצפה — פשוט מדלגים'),
('training.rule1_sub',      'en', 'An open bag stays on the floor — just skip it'),
('training.rule2',          'he', 'עד {kg} ק״ג'),
('training.rule2',          'en', 'Up to {kg} kg'),
('training.rule3',          'he', 'דולפת? תמונה + דילוג'),
('training.rule3',          'en', 'Leaking? Photo + skip'),
('training.rule4',          'he', 'QR בפח בסיום'),
('training.rule4',          'en', 'Scan the bin QR at the end'),
('training.start_cta',      'he', 'יאללה, לעבודה'),
('training.start_cta',      'en', 'Let''s go'),
('training.swipe_hint',     'he', 'החליקו'),
('training.swipe_hint',     'en', 'Swipe'),

-- ── picker feed / stop / collection / finish ───────────────────────────────
('feed.title',              'he', 'בקשות לידך'),
('feed.title',              'en', 'Requests near you'),
('feed.subtitle',           'he', '{count} פתוחות · רדיוס {radius} מ׳'),
('feed.subtitle',           'en', '{count} open · {radius}m radius'),
('feed.available_toggle',   'he', 'זמין'),
('feed.available_toggle',   'en', 'Available'),
('feed.view_list',          'he', 'רשימה'),
('feed.view_list',          'en', 'List'),
('feed.view_map',           'he', 'מפה'),
('feed.view_map',           'en', 'Map'),
('feed.card',               'he', '{distance} מ׳ · {units} שקיות · עד {deadline}'),
('feed.card',               'en', '{distance}m · {units} bags · by {deadline}'),
('feed.building_group',     'he', 'בניין אחד · {count} דיירים'),
('feed.building_group',     'en', 'One building · {count} residents'),
('feed.code_after_claim',   'he', 'הקוד נחשף אחרי תפיסה'),
('feed.code_after_claim',   'en', 'Code revealed after claiming'),
('feed.claim_cta',          'he', 'לתפוס'),
('feed.claim_cta',          'en', 'Claim'),
('feed.claim_all_cta',      'he', 'לתפוס הכול'),
('feed.claim_all_cta',      'en', 'Claim it all'),
('feed.waiting_resident',   'he', '{distance} מ׳ · נודיע ברגע שיאשר'),
('feed.waiting_resident',   'en', '{distance}m · we''ll ping you on approval'),
('feed.already_claimed',    'he', 'נתפסה — הנה הבאה'),
('feed.already_claimed',    'en', 'Taken — here''s the next one'),
('feed.empty',              'he', 'אין בקשות כרגע. נשלח התראה כשמשהו יופיע'),
('feed.empty',              'en', 'No requests right now. We''ll ping you when one appears'),
('feed.tab',                'he', 'בקשות'),
('feed.tab',                'en', 'Requests'),

('stop.title',              'he', 'העצירה שלי'),
('stop.title',              'en', 'My stop'),
('stop.empty',              'he', 'אין עצירה פעילה — תפסו בקשה מהפיד'),
('stop.empty',              'en', 'No active stop — claim one from the feed'),
('stop.entry_code',         'he', 'קוד כניסה · חשיפה מתועדת'),
('stop.entry_code',         'en', 'Entry code · reveals are logged'),
('stop.code_expires',       'he', 'הקוד פעיל ל־{minutes}:{seconds}'),
('stop.code_expires',       'en', 'Code active for {minutes}:{seconds}'),
('stop.no_code',            'he', 'אין קוד לבניין הזה — הדלת פתוחה'),
('stop.no_code',            'en', 'No code for this building — the door''s open'),
('stop.deadline',           'he', 'לאסוף ולסרוק עד {time}'),
('stop.deadline',           'en', 'Collect & scan by {time}'),
('stop.payout_footer',      'he', 'בסיום העצירה'),
('stop.payout_footer',      'en', 'When the stop is done'),
('stop.arrived_cta',        'he', 'הגעתי לבניין'),
('stop.arrived_cta',        'en', 'I''m at the building'),
('stop.navigate',           'he', 'ניווט'),
('stop.navigate',           'en', 'Navigate'),
('stop.release',            'he', 'שחרור העצירה'),
('stop.release',            'en', 'Release this stop'),
('stop.floor_apt',          'he', 'קומה {floor} · דירה {apartment}'),
('stop.floor_apt',          'en', 'Floor {floor} · Apt {apartment}'),
('stop.waiting_resident',   'he', 'ממתינים לאישור הדייר'),
('stop.waiting_resident',   'en', 'Waiting for the resident'),

('collect.title',           'he', 'איסוף — {street}'),
('collect.title',           'en', 'Collection — {street}'),
('collect.unit_check',      'he', 'שקית {n} נאספה'),
('collect.unit_check',      'en', 'Bag {n} collected'),
('collect.chip_small',      'he', '3 קטנות = 1'),
('collect.chip_small',      'en', '3 small = 1'),
('collect.chip_large',      'he', 'שקיות גדולות'),
('collect.chip_large',      'en', 'Large bags'),
('collect.chip_oversized',  'he', '×2 גדולה'),
('collect.chip_oversized',  'en', 'Oversized ×2'),
('collect.chip_overweight', 'he', 'קבוצת הקטנות כבדה מדי'),
('collect.chip_overweight', 'en', 'Small-bag group over the weight cap'),
('collect.counts_as',       'he', 'נספרת כ־{units}'),
('collect.counts_as',       'en', 'Counts as {units}'),
('collect.leak_cta',        'he', 'דולפת? צלמו ודלגו'),
('collect.leak_cta',        'en', 'Leaking? Photo & skip'),
('collect.leak_note',       'he', 'בלי קנס · הדייר מקבל עדכון אוטומטי'),
('collect.leak_note',       'en', 'No penalty · the resident is updated automatically'),
('collect.done_cta',        'he', 'לסריקת ה־QR בפח'),
('collect.done_cta',        'en', 'To the bin QR scan'),
('collect.done_note',       'he', 'הסריקה סוגרת את העצירה ומשחררת את התשלום'),
('collect.done_note',       'en', 'The scan closes the stop and releases the payout'),

('finish.scan_title',       'he', 'סרקו את ה־QR שעל הפח'),
('finish.scan_title',       'en', 'Scan the QR on the bin'),
('finish.scanned',          'he', '✓ נסרק — פח בניין · {street}'),
('finish.scanned',          'en', '✓ Scanned — building bin · {street}'),
('finish.wrong_qr',         'he', 'זה לא ה־QR של הבניין הזה'),
('finish.wrong_qr',         'en', 'That''s not this building''s QR'),
('finish.celebration',      'he', '+{amount} · סה״כ היום {total}'),
('finish.celebration',      'en', '+{amount} · today''s total {total}'),
('finish.daily_goal',       'he', 'היעד היומי'),
('finish.daily_goal',       'en', 'Daily goal'),
('finish.next_cta',         'he', 'לבקשה הבאה'),
('finish.next_cta',         'en', 'Next request'),
('finish.enough_cta',       'he', 'מספיק להיום'),
('finish.enough_cta',       'en', 'Enough for today'),
('common.camera_permission','he', 'צריך הרשאת מצלמה כדי להמשיך'),
('common.camera_permission','en', 'Camera permission is needed to continue'),
('common.continue',         'he', 'ממשיכים'),
('common.continue',         'en', 'Continue'),

('earnings.title',          'he', 'רווחים'),
('earnings.title',          'en', 'Earnings'),
('earnings.today',          'he', 'היום'),
('earnings.today',          'en', 'Today'),
('earnings.week',           'he', 'שבוע'),
('earnings.week',           'en', 'Week'),
('earnings.month',          'he', 'חודש'),
('earnings.month',          'en', 'Month'),
('earnings.stats_line',     'he', '{stops} עצירות · {units} שקיות · ממוצע {avg} לעצירה'),
('earnings.stats_line',     'en', '{stops} stops · {units} bags · {avg} avg per stop'),
('earnings.net_hint',       'he', '{net} נטו לשקית'),
('earnings.net_hint',       'en', '{net} net per bag'),
('earnings.payout_schedule','he', 'העברה הבאה — יום {day}'),
('earnings.payout_schedule','en', 'Next transfer — {day}'),
('earnings.payout_method',  'he', '{bank} ••{last4} · אוטומטית, כל שבוע'),
('earnings.payout_method',  'en', '{bank} ••{last4} · automatic, weekly'),
('earnings.ledger_day',     'he', '{day} · {stops} עצירות'),
('earnings.ledger_day',     'en', '{day} · {stops} stops'),
('earnings.invoices',       'he', 'ארכיון חשבוניות'),
('earnings.invoices',       'en', 'Invoice archive'),
('earnings.invoice_line',   'he', '{number} · {month} · הופקה בשבילך'),
('earnings.invoice_line',   'en', '{number} · {month} · issued for you'),
('earnings.strikes',        'he', 'נקודות: {count}/{max}'),
('earnings.strikes',        'en', 'Strikes: {count}/{max}'),
('earnings.tab',            'he', 'רווחים'),
('earnings.tab',            'en', 'Earnings'),
('profile.tab',             'he', 'פרופיל'),
('profile.tab',             'en', 'Profile'),

-- ── push templates ──────────────────────────────────────────────────────────
('push.requests_nearby.title', 'he', '{count} בקשות לידך'),
('push.requests_nearby.title', 'en', '{count} requests near you'),
('push.requests_nearby.body',  'he', 'כולן כבר בחוץ — שווה לרדת עכשיו · {amount}'),
('push.requests_nearby.body',  'en', 'All already outside — worth going down · {amount}'),
('push.request_claimed.title', 'he', 'שליח תפס — השקית בדרך למטה'),
('push.request_claimed.title', 'en', 'Claimed — your bag''s on its way down'),
('push.request_claimed.body',  'he', 'האיסוף עד {deadline} · אין צורך בכלום'),
('push.request_claimed.body',  'en', 'Pickup by {deadline} · nothing needed'),
('push.request_done.title',    'he', 'נאספה ונסרקה בפח ✓'),
('push.request_done.title',    'en', 'Collected & scanned ✓'),
('push.request_done.body',     'he', 'הבקשה נסגרה · תודה שאתם למטה'),
('push.request_done.body',     'en', 'Request closed · thanks for being with Lemata'),
('push.request_expired.title', 'he', 'לא הסתדר היום — קיבלתם זיכוי'),
('push.request_expired.title', 'en', 'Didn''t work out today — you got a credit'),
('push.request_expired.body',  'he', 'שקית זיכוי נוספה אוטומטית · אפשר לנסות שוב מתי שרוצים'),
('push.request_expired.body',  'en', 'A credit bag was added automatically · try again anytime'),
('push.request_leak.title',    'he', 'השקית לא נאספה — היא דולפת'),
('push.request_leak.title',    'en', 'Bag not collected — it''s leaking'),
('push.request_leak.body',     'he', 'לא חויבתם. עטפו שוב ופרסמו מחדש'),
('push.request_leak.body',     'en', 'You weren''t charged. Re-bag and post again'),
('push.units_adjusted.title',  'he', 'עדכון כמות באיסוף'),
('push.units_adjusted.title',  'en', 'Pickup quantity updated'),
('push.units_adjusted.body',   'he', 'הכמות עודכנה ל־{units} שקיות'),
('push.units_adjusted.body',   'en', 'Updated to {units} bags'),
('push.approve_eta.title',     'he', 'שליח מוכן לרדת אליכם'),
('push.approve_eta.title',     'en', 'A courier is ready to head down'),
('push.approve_eta.body',      'he', 'אשרו את האיסוף באפליקציה'),
('push.approve_eta.body',      'en', 'Approve the pickup in the app'),
('push.put_out.title',         'he', 'השליח בדרך — הוציאו את השקית'),
('push.put_out.title',         'en', 'Courier''s on the way — put the bag out'),
('push.put_out.body',          'he', 'אשרו באפליקציה כשהשקית בחוץ'),
('push.put_out.body',          'en', 'Confirm in the app once it''s outside'),
('push.claim_lapsed.title',    'he', 'העצירה לא הושלמה בזמן'),
('push.claim_lapsed.title',    'en', 'The stop wasn''t completed in time'),
('push.claim_lapsed.body',     'he', 'הבקשה חזרה ללוח וקיבלת נקודה'),
('push.claim_lapsed.body',     'en', 'The request was reposted and you received a strike'),
('push.picker_suspended.title','he', 'החשבון הושהה'),
('push.picker_suspended.title','en', 'Account suspended'),
('push.picker_suspended.body', 'he', 'הצטברו {count} נקודות. דברו איתנו לבירור'),
('push.picker_suspended.body', 'en', '{count} strikes accumulated. Contact us to review'),
('push.referral_reward.title', 'he', 'קיבלתם {units} שקיות מתנה 🎁'),
('push.referral_reward.title', 'en', 'You got {units} free bags 🎁'),
('push.referral_reward.body',  'he', 'תודה שהזמנתם שכנים'),
('push.referral_reward.body',  'en', 'Thanks for inviting your neighbors'),
('push.meter_tier.title',      'he', 'הבניין שלכם שובר שיאים 🏢'),
('push.meter_tier.title',      'en', 'Your building is on a roll 🏢'),
('push.meter_tier.body',       'he', '{doors} דלתות פעילות — כולם קיבלו {bonus} שקיות'),
('push.meter_tier.body',       'en', '{doors} active doors — everyone got {bonus} bags'),
('push.payout_sent.title',     'he', 'ההעברה השבועית יצאה 💸'),
('push.payout_sent.title',     'en', 'Weekly payout sent 💸'),
('push.payout_sent.body',      'he', '{amount} בדרך לחשבון שלך'),
('push.payout_sent.body',      'en', '{amount} on its way to your account'),

-- ── sms ─────────────────────────────────────────────────────────────────────
('sms.otp_body',                 'he', 'קוד הכניסה שלך ללמטה: {otp}'),
('sms.otp_body',                 'en', 'Your Lemata sign-in code: {otp}'),

-- ── self-billed invoice + QR poster (rendered server/admin side) ───────────
('invoice.title',                'he', 'חשבונית עצמית (Self-Billed)'),
('invoice.title',                'en', 'Self-Billed Invoice'),
('invoice.issued_note',          'he', 'הופקה מכוח ייפוי כוח לחיוב עצמי'),
('invoice.issued_note',          'en', 'Issued under a self-billing power of attorney'),
('invoice.supplier',             'he', 'ספק'),
('invoice.supplier',             'en', 'Supplier'),
('invoice.vat_dealer',           'he', 'עוסק {vat_id}'),
('invoice.vat_dealer',           'en', 'Dealer no. {vat_id}'),
('invoice.col_item',             'he', 'פירוט'),
('invoice.col_item',             'en', 'Item'),
('invoice.col_amount',           'he', 'סכום'),
('invoice.col_amount',           'en', 'Amount'),
('invoice.line_pickups',         'he', 'איסוף ופינוי — {units} שקיות'),
('invoice.line_pickups',         'en', 'Collection & disposal — {units} bags'),
('invoice.vat_label',            'he', 'מע"מ ({pct}%)'),
('invoice.vat_label',            'en', 'VAT ({pct}%)'),
('invoice.total_due',            'he', 'סה"כ לתשלום'),
('invoice.total_due',            'en', 'Total due'),
('invoice.print_hint',           'he', 'להפקת PDF: הדפסה ← שמירה כ-PDF'),
('invoice.print_hint',           'en', 'For a PDF: Print → Save as PDF'),
('invoice.masav_header',         'he', 'LEMATA PAYOUTS'),
('invoice.masav_header',         'en', 'LEMATA PAYOUTS'),
('qr_poster.scan_hint',          'he', 'סרקו כאן בסיום האיסוף'),
('qr_poster.scan_hint',          'en', 'Scan here when the pickup is done'),

-- ── errors (stable RPC codes → copy) ───────────────────────────────────────
('error.already_claimed',        'he', 'נתפסה כבר — נסו את הבאה'),
('error.already_claimed',        'en', 'Already claimed — try the next one'),
('error.insufficient_allowance', 'he', 'נגמרה המכסה החודש'),
('error.insufficient_allowance', 'en', 'No bags left this month'),
('error.illegal_transition',     'he', 'הפעולה לא אפשרית במצב הנוכחי'),
('error.illegal_transition',     'en', 'That action isn''t possible right now'),
('error.claim_expired',          'he', 'זמן העצירה עבר'),
('error.claim_expired',          'en', 'The stop window has passed'),
('error.claim_limit_reached',    'he', 'סיימו את העצירה הנוכחית לפני שתופסים חדשה'),
('error.claim_limit_reached',    'en', 'Finish your current stop before claiming another'),
('error.building_paused',        'he', 'השירות בבניין הזה מושהה זמנית'),
('error.building_paused',        'en', 'Service in this building is temporarily paused'),
('error.service_disabled',       'he', 'השירות מושהה זמנית — חוזרים ממש בקרוב'),
('error.service_disabled',       'en', 'Service is temporarily paused — back very soon'),
('error.not_authorized',         'he', 'אין הרשאה לפעולה הזו'),
('error.not_authorized',         'en', 'You''re not authorized to do that'),
('error.not_found',              'he', 'לא נמצא'),
('error.not_found',              'en', 'Not found'),
('error.picker_not_active',      'he', 'החשבון עדיין לא אושר לעצירות'),
('error.picker_not_active',      'en', 'Your account isn''t approved for stops yet'),
('error.picker_suspended',       'he', 'החשבון מושהה'),
('error.picker_suspended',       'en', 'Your account is suspended'),
('error.rate_limited',           'he', 'יותר מדי ניסיונות — נסו שוב עוד רגע'),
('error.rate_limited',           'en', 'Too many attempts — try again in a moment'),
('error.invalid_qr',             'he', 'זה לא ה־QR של הבניין הזה'),
('error.invalid_qr',             'en', 'That''s not this building''s QR code'),
('error.photo_required',         'he', 'חובה לצרף תמונה'),
('error.photo_required',         'en', 'A photo is required'),
('error.underage',               'he', 'אפשר להצטרף רק מגיל 18'),
('error.underage',               'en', 'You must be 18 or older'),
('error.invalid_units',          'he', 'כמות שקיות לא תקינה'),
('error.invalid_units',          'en', 'Invalid number of bags'),
('error.ttl_passed',             'he', 'המועד הזה כבר עבר להיום — בחרו מועד אחר'),
('error.ttl_passed',             'en', 'That deadline already passed today — pick another'),
('error.subscription_not_active','he', 'אין מנוי פעיל'),
('error.subscription_not_active','en', 'No active subscription'),
('error.feature_disabled',       'he', 'האפשרות הזו לא זמינה כרגע'),
('error.feature_disabled',       'en', 'This option isn''t available right now'),
('error.config_validation_failed','he', 'ערך לא תקין להגדרה הזו'),
('error.config_validation_failed','en', 'Invalid value for this setting'),
('error.unknown',                'he', 'משהו השתבש — נסו שוב'),
('error.unknown',                'en', 'Something went wrong — try again')

on conflict (key, locale) do nothing;
